site_name: replaybg
site_description: ReplayBG digital twinning framework

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            show_if_no_docstring: true
            show_source: true
            docstring_style: google
            filters:
              - "!^__(?!init)"    # hide dunder except __init__

nav:
  - Home: index.md
  - API Reference:
    - Data: api/data.md
    - Distributions: api/distributions.md
    - Environment: api/environment.md
    - Model: api/model.md
    - Simulator: api/simulator.md
    - Twinner: api/twinner.md
    - Utils: api/utils.md