site_name: replaybg
site_description: Replay background simulation

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]  # root of your project

nav:
  - Home: index.md
  - API Reference:
    - Data: api/data.md
    - Distributions: api/distributions.md
    - Environment: api/environment.md
    - Model: api/model.md
    - Simulator: api/simulator.md
    - Twinner: api/twinner.md
    - Utils: api/utils.md